
[package]
name = "candle-whisper-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
hound = "3.5.1"
rustfft = "6.4.0"
serde_json = "1.0.141"
tokenizers = "0.21.2"
wasm-bindgen = "0.2"
